### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by brianjmurrell** [learningit/plugin.video.cbc#3]
Looks like perhaps the HTML has changed:

```
12:52:33 T:140077640148736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/home/brian/.kodi/addons/plugin.video.cbc/default.py", line 276, in <module>
                                                if mode==  None:  getSources(p('fanart'))
                                              File "/home/brian/.kodi/addons/plugin.video.cbc/default.py", line 107, in getSources
                                                html = re.compile('<div id="catnav">(.+?)<div id="cliplist">').search(html).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
12:52:34 T:140079433431424   ERROR: GetDirectory - Error getting plugin://plugin.video.cbc/
12:52:34 T:140079433431424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/) failed
```

**Comment by learningit** [comment]
Please see the support thread. http://forum.kodi.tv/showthread.php?tid=222347
